### ISSUE TITLE
.gitattributes not properly configured

### ISSUE THREAD

**Issue by sparsh-ai** [Sandeep-Panchal/Job_Recommendation_Deployment#1]
.gitattributes file has not been properly configured - unable to download data files from git-lfs

**Comment by Sandeep-Panchal** [comment]
Thanks @sparsh-ai  for bringing this to my notice. I will look into this and get back as early as possible.

**Comment by Sandeep-Panchal** [comment]
@sparsh-ai I tried downloading the zip from the **Code dropdown**. Yes, data files are not getting downloaded properly. I tried few possible things and figured out one way to download the files. Instead of downloading, you can easily **clone the repository**. 

**"From the Code dropdown, -> select the HTTPS option -> copy the link -> open Git CMD or CMD whatever you have in your local system -> navigate to the directory wherever you want to clone -> type 'git clone' and paste the link that you copied**
 (git clone https://github.com/Sandeep-Panchal/Job_Recommendation_Deployment.git) 

Let me know if you face any issue.

**Comment by Sandeep-Panchal** [comment]
Closing issue
